import { APP_URL } from "./Host";

export const ApiConstants = {
	SENDOTP: APP_URL + '/accounts/riders/create/',
	VERIFYOTP: APP_URL + '/accounts/phone/verify/otp/',
	RIDERDETAILS: APP_URL + '/accounts/riders/',
	USERLOGOUT: APP_URL + '/accounts/riders/logout/',
	QUOTATIONAPI: APP_URL + '/riders/ride/quotation/',
	CENCELRIDE: APP_URL + '/riders/driver/cancel/ride/',
	FEEDBACKAPI: APP_URL + '/riders/ride/feedback/',
	CONTACTLIST: APP_URL + '/accounts/user/emergency/contact/',
	CREATERIDE: APP_URL + '/riders/ride/',
	RIDEDETAILS: APP_URL + '/riders/ride/',
	CREATEEMERGENCYCONTACT: APP_URL + '/accounts/user/emergency/contact/',
	DELETECONTACT: APP_URL + '/accounts/user/emergency/contact/',
	RIDERBOOKLATER: APP_URL + '/riders/drivers/ride/',
	FINDDRIVER: APP_URL + '/riders/find/driver/',
	RIDERACTIVERIDE: APP_URL + '/riders/rider/active/ride/',
	ADDSAVEPLACE: APP_URL + '/riders/save-places/',
	SAVEPLACESLIST: APP_URL + '/riders/save-places/',
	REMOVESAVEPLACE: APP_URL + '/riders/save-places/',
	RECENTPLACESLIST: APP_URL + '/riders/recent-places/',
	STARTRIDEDRIVERLOCATION: APP_URL + '/riders/drivers/location/',
	MESSAGELIST: APP_URL + '/riders/chat-room/message/',
	NOTIFICATIONLIST: APP_URL + '/accounts/notifications/',
	MARKALLNOTIFICATION: APP_URL + '/accounts/mark-all-read/',
	DELETERIDEBOOKING: APP_URL + '/riders/ride/delete/',
	SENDSOSMESSAGE: APP_URL + '/riders/send-message/',
	DELETEDOCUMENT: APP_URL + '/riders/riders-document/delete/',
	MAKE_PAYMENT: APP_URL + '/riders/make-payment/',
	DELETE_ACCOUNT: APP_URL + "/accounts/delete-account/",
	UPDATE_CHAT_LANGUAGE: APP_URL + '/accounts/update-language/',
	ENABLE_SECURE_MODE: APP_URL + '/riders/update-secure-mode/',
	GET_DISCOUNT_COUPON: APP_URL + '/riders/discount_coupon_list/',
	APPLY_DISCOUNT_COUPON: APP_URL + "/riders/apply_coupon/",
	GET_WALLET_DETAILS: APP_URL + '/accounts/wallet/',
	WITHDRAW_MONEY: APP_URL + '/accounts/withdraw-money/',
	WITHDRAW_WALLET_HISTORY: APP_URL + '/accounts/withdrawal-wallet-history/',
	SCRTACH_CARD_DETAILS : APP_URL + '/riders/ride-scratch-coupons/by-ride-booking/',
	SCRTACH_CARD_LIST: APP_URL + '/riders/ride-scratch-coupons/',
	SCRTACH_CARD_LIST_EDIT: APP_URL + '/riders/ride-scratch-coupons/',
	CHAT_LANGUAGE: APP_URL + "/accounts/update-chat-language/",
	RIDE_BILL_PDF: APP_URL + "/riders/download-pdf/",
	API_COUNTER: APP_URL + "/accounts/api-call-log/",
	GOODS_INFO: APP_URL + "/admins/goods-info/",
	CREATE_DELIVERY_RIDE: APP_URL + "/riders/delivery/booking/",
	PAYMENT_BEFORE_AFTER: APP_URL + "/admins/payment-gateway/",
	ENDRIDE_CARD_PAYMENT: APP_URL + "/riders/end-ride/card-payment/",
	RIDER_APP_STATE: APP_URL + "/riders/app-status/",
	COMMON_CREDENTIALS: APP_URL + "/accounts/common-credentials/"
};
