export const ANALYTICS_ID = {
    IS_FIRST_TIME_OPENED_APP: "IS_FIRST_TIME_OPENED_APP",
    USER_REGISTER_SUCCESSFULLY: "USER_REGISTER_SUCCESSFULLY",
    GO_TO_DESTINATION_LOCATION_SCREEN: "GO_TO_DESTINATION_LOCATION_SCREEN",
    GO_TO_RIDE_BOOKING_SCREEN: "GO_TO_RIDE_BOOKING_SCREEN",
    RIDE_BOOKING_SUCCESSFULLY: "RIDE_BOOKING_SUCCESSFULLY",
    RIDE_CANCELLED: "RIDE_CANCELLED",
    YOUR_RIDER_SCREEN: "YOUR_RIDER_SCREEN",
    RIDE_PAYMENT_COMPLETED: "RIDE_PAYMENT_COMPLETED",
    SOS_REQUEST_SENT: "SOS_REQUEST_SENT"
}