export const AppStrings = {
    is_first_time_open: "isFirstTimeOpen",
    pre_book_your_ride: "Pre - Book your ride",
    choose_the_route: "Choose the route",
    track_your_ride: "Track your ride",
    finish: "Finish",
    skip: "Skip",
    enter_phone_number: "Enter Phone number for verification",
    this_number_will_be_used: "This number will be used for all ride-related communication. You shall receive an SMS with code for verification.",
    otp: "OTP",
    otp_verification: "OTP Verification",
    code_has_been_sent_to: "Code has been sent to",
    did_not_receive_otp: "Didn’t receive OTP?",
    resend_code: "Resend code",
    send_otp: "Send OTP",
    verify_otp: "Verify OTP",
    name: "Name",
    enter_your_name: "Enter Your Name",
    confirm: "Confirm",
    enter_phonenumber: "Enter phone number",
    phone_number_is_requried: "Phone number is requried",
    please_enter_valid_phone_number: "Please Enter valid phone number",
    please_enter_valid_otp: "Please Enter Valid OTP",
    please_enter_otp: "Please Enter OTP",
    please_enter_name: "Please enter name*",
    current_location: "Current Location",
    where_to: "Where to?",
    recent_locations_not_found: "Recent locations not found",
    destination: "Destination",
    saved_places: "Saved Places",
    confirm_location: "Confirm Location",
    pick_up: "Pick-up",
    enter_location: "Enter drop-out location",
    book_ride: "Book Ride",
    confirm_ride: "Confirm Ride",
    rupee_symbol: "AED",
    per_km: "/per km",
    seats_capacity: "Seats Capacity",
    cash: "Cash",
    book_for_self: "Book for self",
    now: "Now",
    someone_else_taking_ride: "Someone else taking this ride?",
    choose_a_contact: "Choose a contact so that they also get driver number, vehicle details and ride OTP vis SMS.",
    myself: "My self",
    choose_another_contacts: "Choose another contacts",
    book: "Book",
    emergency_contacts: "Emergency Contact",
    add_new_contact: "Add new contact",
    select_contacts: "Select Contacts",
    relationship: "Relationship",
    enter_relationship: "Enter Relationship",
    add_emergency_contact: "Add Emergency Contact",
    please_enter_relationship: "Please enter Relationship",
    ride_founded: "Ride Founded",
    request_ride: "Request Ride",
    ride_not_found: "Ride Not Found",
    please_try_again_in_a_few_minutes: "please try again in a few minutes",
    try_again: "Try Again",
    driver_is_arriving: "Driver is Arriving...",
    ride_started: "Ride started",
    ride_completed: "Ride completed",
    ride_cancelled: "Ride cancelled",
    are_your_estimated_fares_for_your_ride: "are your estimated fares for your ride",
    cancel: "Cancel",
    //?
    // Drawer Screen Strings
    welcome: "Welcome",
    edit_profile: "Edit Profile",
    notification: "Notifications",
    your_rides: "Your Rides",
    pre_booked: "Pre - Booked",
    privacy_policy: "Privacy Policy",
    help_center: "Help Center",
    emergency_contact: "Emergency Contact",
    delete_account: "Delete Account",
    logout: "Log Out",
    version: "V 1.0.0",
    // Cencel Taxi Strings
    cancel_taxi: "Cancel Ride",
    select_cancellations_reason: "Please select the reason for cancellation:",
    cancellations_reason: {
        plan_changed: "Plan changed",
        booked_another_cab: "Booked another cab",
        my_reason_is_not_listed: "My reason is not listed",
        driver_is_not_picking_phone: "Driver is not picking up the call",
        waiting_time_is_too_long: "Waiting time is too long",
        taking_too_long_time_to_find_cab: "Taking too long to find the cab"
    },
    pre_cancellations_reason: {
        not_confident_about_ride: "Didn't feel confident about the ride",
        no_need_ride: "No longer need this ride",
        different_ride: "Taking a different ride on RYD Now",
        no_diver_assigned: "No driver assigned",
        my_reason_is_not_listed: "My reason is not listed",
    },
    disputed_reason: {
        driver_took_longer_route:"Driver Took a Longer Route Intentionally",
        driver_was_rude:"Driver Was Rude or Unprofessional",
        driver_ask_extra_payment:"Driver Asked for Extra Payment",
        driver_made_stop:"Driver Made an Unwanted Stop",
        driver_under_alcohol:"Driver Under the Influence of Alcohol or Drugs",
        driver_brought_people:"Driver Brought Additional People in Vehicle",
        please_specify_other:"Other (Please Specify)"
    },
    other: "Other",
    enter_your_reason: "Enter your Reason",
    cancel_ride: "Cancel Ride",
    booking_Cancelled: "Booking Cancelled",
    cancelStatement: "Your booking with CRN1308944058 has been cancelled successfully.",
    got_it: "Got it",
    rate_driver: "Rate Driver",
    byron_barlow: "Byron Barlow",
    innova_crysta: "Innova Crysta",
    carno: "GJ05NB9654",
    how_was_your_trip_with: "How was your trip with",
    submit: "Submit",
    comment: "Comment",
    write_here: "Write here..",
    add_a_tip_to: "Add a tip to",
    rs5: "₹5",
    rs10: "₹10",
    rs20: "₹20",
    rs50: "₹50",
    cancelation_policy: "Cancelation Policy",
    terms_condition: "Terms & Condition",
    account: "Account",
    safety: "Safety",
    services: "Services",
    general: "General",
    customer_service: "Customer Service",
    whatsapp: "WhatsApp",
    website: "Website",
    facebook: "Facebook",
    twitter: "Twitter",
    instagram: "Instagram",
    email: "E-Mail",
    optional: "Optional",
    mobileno: "Mobile Number",
    update_changes: "Update Changes",
    profile_updated_successfully: "Profile updated successfully!",

    // search rider screen
    searching_ride_header: "Searching Ride",
    searching_ride: "Searching Ride...",
    this_mmay_take_a_few_seconds: "This may take a few seconds...",
    // Your rides
    date_and_time: "Date & Time",
    vehicle_number: "Vehicle Number",
    track_driver: "Track Driver",
    no_of_seats: "No. of Seats",
    by: "by",
    seater: "Seater",
    sos: "SOS",
    use_in_case_of_emergency: "USE IN CASE OF EMERGENCY",
    call_police_control_room: "Call Police Control Room",
    alert_your_emergency_contacts: "Alert your Emergency contacts",
    company_collects_location: "Company Collects location during an active booking from your device, including when the app in the background. This data is used to ensure that Company name users have a safe and smooth ride experience.",
    continue_to_send_alert: "Continue to send Alert?",
    sending_alert: "Sending Alert...",
    alert_sent: "Alert Sent",
    continue: "Continue",
    select_all: "Select All",
    alert_now: "Alert Now",
    type_a_message: "Type a message...",
    ok: "Ok",
    are_you_sure_you_want_to_log_out: "Are you sure you want to log out?",
    yes_log_out: "Yes, Logout",
    something_went_wrong: "Something went wrong",
    please_enter_email: "Please enter email",
    please_enter_valid_email: "Please enter valid email",
    enter_name: "Enter Name",
    enter_email_address: "Enter email address",
    please_enter_your_name: "Please enter your name",
    error: "Message",
    device_is_not_connected: "Oops! Looks like your device is not connected to the Internet.",
    connection_error: "Connection Error",
    your_seesion_has_expired: "Your Session has expired! Please login again",
    you_cannot_select_more_than_location: "You cann't select more than 6 location",
    warning: "Warning",
    select_payment_mode: "Select Payment Mode",
    credit_debit_cards: "Credit / Debit cards",
    cards: "Cards",
    or: "or",
    enter_pick_up_location: "Enter pick-up location",
    please_select_reason_or_enter_a_reason_of_cancellation: "Please Select Reason or Enter a Reason of Cancellation",
    search_contacts: "Search contacts",
    contacts_not_found: "Contacts not found",
    select_pick_up_time: "Select pick-up time",
    pre_booked_ride_data_not_found: "Pre booked ride data not found",
    ride_data_not_found: "ride data not found",
    selected_location_already_exist: "Selected location already exist please select another location",
    pay_now: "Pay now",
    location_save_successfully: "Location Save Successfully",
    save_places_not_found: "Save places Not Found",
    recent_places_not_found: "Recent places Not Found",
    booking_statement: "Your Ride is Successfully Booked",
    ride_booked_successfully: "Congratulations!",
    find_driver: "Find driver",
    no_notification_yet: "No notification yet",
    when_you_get_notification_they_will_show_up_here: "When you get notifications, they'll show up here",
    cancellation_statement: "Your booking has been cancelled due to",
    payment_statement: "Your Payment has successfully accomplished",
    payment_success: "Payment Successful",
    name_cannot_containe_number: "* Name cannot contain number or any special character",
    location_permission: "Turn on Location Services to allow \"RYD\" to determine your location.",
    go_to_settings: "Go to Settings",
    please_wait: 'Please wait ...',
    //
    Customer_Identification: "Customer Identification",
    welcome_to_driverapp: "Welcome to Company Passenger App!",
    please_enter_required_details: "Please enter required details",
    done: "Done",
    dropdown_now: "NOW",
    dropdown_later: "LATER",
    document_uploaded_successfully: "Document Uploaded Successfully",
    //
    add_custom_tip: "Add custom tip",
    documents: "Documents",
    update_document_details: "Update Document Details",
    //
    add_stop: "Add Stop",
    save_Place: "Save Place",
    make_payment: "Make Payment",
    are_you_sure_you_want_to_delete_account: "Are you sure you want to delete your account ?",
    yes_delete_it: "Yes Delete it",
    //
    toll_tax: "Toll-Tax",
    emergeny_contacts: "Emergency Contact",
    enter_your_adhar_card_no: "Enter Aadhaar Card Number",
    enter_your_passport_no: "Enter Passport Number",
    please_enter_valid_aadhar_card_number: "Please Enter Valid Aadhaar Card Number",
    please_enter_passport_number: "Please Enter Valid Passport Number",
    read_more: "Read More.",
    waiting_drivers_payment_approval: "Waiting for approval regarding the driver's payment",
    discount_coupons: "Discount Coupons",
    apply_now: "Apply Now",
    refer_earn: "Refer & Earn",
    total_reward: "TOTAL REWARD",
    refer: "Refer and earn!",
    invite_friend_to_join_app: "Invite friends to join the app using your referral code and earn rewards together!",
    copy: "Copy",
    successFullyCodeCopied: "Referal Code Copied",
    how_it_work: "How it works?",
    share_your_code: "Share your code",
    people_signup: "People sign up",
    they_book_ride: "They complete their first ride",
    both_earn_reward: "Both earn rewards",
    gender: "Gender",
    please_select_gender: "Please Select Gender",
    referral_code: "Referral Code",
    referral_code_copied_successfully: "Referral Code Copied Successfully",
    oops: "Oops!",
    discount_not_found: "It seems we couldn't find any coupons for you this time. But don't worry, new offers are added regularly. Stay tuned for future discounts by joining our community today!",
    enable_secure_mode_to_enable: "Activate Secure Mode to ensure your ride is completed by verified drivers who prioritize your safety for a hassle-free journey.",
    auto_bike_are_not_allowed: "Auto and Bikes are not allowed for secure cab",
    selected_language: "selectedLanguage",
    service_taxes: "Service Tax",
    updated_successfully: "Updated successfully!",
    please_select_another_image: "Please select another image",
    enter_bank_name: "Enter Bank Name",
    enter_account_number: "Enter Account Number",
    enter_ifsce_code: "Enter IFSC code",
    enter_account_holder_name: "Enter Account Holder Name",
};
